# Generated by Django 3.1.12 on 2024-12-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdomainassociation',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessdomainassociation',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='businessdomainservice',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='businessuserassociation',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessuserassociation',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='toto', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='tata', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='1111111111', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessDomain',
        ),
        migrations.DeleteModel(
            name='BusinessDomainAssociation',
        ),
        migrations.DeleteModel(
            name='BusinessDomainService',
        ),
        migrations.DeleteModel(
            name='BusinessUserAssociation',
        ),
    ]
