# Generated by Django 3.1.12 on 2024-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit_api', '0005_auto_20241206_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
