# Generated by Django 3.1.12 on 2024-12-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookit_api', '0010_booking_business_service_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='business',
        ),
    ]
